const axios = require("axios");

const portPair = [
  "Marseille-Ho Chi Minh City",
  "Marseille-Haiphong",
  "Marseille-Da Nang",
  "Le Havre-Ho Chi Minh City",
  "Le Havre-Haiphong",
  "Le Havre-Da Nang",
  "Bordeaux-Ho Chi Minh City",
  "Bordeaux-Haiphong",
  "Bordeaux-Da Nang",
  "Marseille-Genoa",
  "Marseille-Naples",
  "Marseille-Venice",
  "Le Havre-Genoa",
  "Le Havre-Naples",
  "Le Havre-Venice",
  "Bordeaux-Genoa",
  "Bordeaux-Naples",
  "Bordeaux-Venice",
  "Marseille-Barcelona",
  "Marseille-Valencia",
  "Marseille-Malaga",
  "Le Havre-Barcelona",
  "Le Havre-Valencia",
  "Le Havre-Malaga",
  "Bordeaux-Barcelona",
  "Bordeaux-Valencia",
  "Bordeaux-Malaga",
  "Marseille-Buenos Aires",
  "Marseille-Rosario",
  "Marseille-Mar del Plata",
  "Le Havre-Buenos Aires",
  "Le Havre-Rosario",
  "Le Havre-Mar del Plata",
  "Bordeaux-Buenos Aires",
  "Bordeaux-Rosario",
  "Bordeaux-Mar del Plata",
  "Marseille-Tokyo",
  "Marseille-Osaka",
  "Marseille-Yokohama",
  "Le Havre-Tokyo",
  "Le Havre-Osaka",
  "Le Havre-Yokohama",
  "Bordeaux-Tokyo",
  "Bordeaux-Osaka",
  "Bordeaux-Yokohama",
  "Marseille-New York",
  "Marseille-Los Angeles",
  "Marseille-Miami",
  "Le Havre-New York",
  "Le Havre-Los Angeles",
  "Le Havre-Miami",
  "Bordeaux-New York",
  "Bordeaux-Los Angeles",
  "Bordeaux-Miami",
  "Ho Chi Minh City-Genoa",
  "Ho Chi Minh City-Naples",
  "Ho Chi Minh City-Venice",
  "Haiphong-Genoa",
  "Haiphong-Naples",
  "Haiphong-Venice",
  "Da Nang-Genoa",
  "Da Nang-Naples",
  "Da Nang-Venice",
  "Ho Chi Minh City-Barcelona",
  "Ho Chi Minh City-Valencia",
  "Ho Chi Minh City-Malaga",
  "Haiphong-Barcelona",
  "Haiphong-Valencia",
  "Haiphong-Malaga",
  "Da Nang-Barcelona",
  "Da Nang-Valencia",
  "Da Nang-Malaga",
  "Ho Chi Minh City-Buenos Aires",
  "Ho Chi Minh City-Rosario",
  "Ho Chi Minh City-Mar del Plata",
  "Haiphong-Buenos Aires",
  "Haiphong-Rosario",
  "Haiphong-Mar del Plata",
  "Da Nang-Buenos Aires",
  "Da Nang-Rosario",
  "Da Nang-Mar del Plata",
  "Ho Chi Minh City-Tokyo",
  "Ho Chi Minh City-Osaka",
  "Ho Chi Minh City-Yokohama",
  "Haiphong-Tokyo",
  "Haiphong-Osaka",
  "Haiphong-Yokohama",
  "Da Nang-Tokyo",
  "Da Nang-Osaka",
  "Da Nang-Yokohama",
  "Ho Chi Minh City-New York",
  "Ho Chi Minh City-Los Angeles",
  "Ho Chi Minh City-Miami",
  "Haiphong-New York",
  "Haiphong-Los Angeles",
  "Haiphong-Miami",
  "Da Nang-New York",
  "Da Nang-Los Angeles",
  "Da Nang-Miami",
  "Genoa-Barcelona",
  "Genoa-Valencia",
  "Genoa-Malaga",
  "Naples-Barcelona",
  "Naples-Valencia",
  "Naples-Malaga",
  "Venice-Barcelona",
  "Venice-Valencia",
  "Venice-Malaga",
  "Genoa-Buenos Aires",
  "Genoa-Rosario",
  "Genoa-Mar del Plata",
  "Naples-Buenos Aires",
  "Naples-Rosario",
  "Naples-Mar del Plata",
  "Venice-Buenos Aires",
  "Venice-Rosario",
  "Venice-Mar del Plata",
  "Genoa-Tokyo",
  "Genoa-Osaka",
  "Genoa-Yokohama",
  "Naples-Tokyo",
  "Naples-Osaka",
  "Naples-Yokohama",
  "Venice-Tokyo",
  "Venice-Osaka",
  "Venice-Yokohama",
  "Genoa-New York",
  "Genoa-Los Angeles",
  "Genoa-Miami",
  "Naples-New York",
  "Naples-Los Angeles",
  "Naples-Miami",
  "Venice-New York",
  "Venice-Los Angeles",
  "Venice-Miami",
  "Barcelona-Buenos Aires",
  "Barcelona-Rosario",
  "Barcelona-Mar del Plata",
  "Valencia-Buenos Aires",
  "Valencia-Rosario",
  "Valencia-Mar del Plata",
  "Malaga-Buenos Aires",
  "Malaga-Rosario",
  "Malaga-Mar del Plata",
  "Barcelona-Tokyo",
  "Barcelona-Osaka",
  "Barcelona-Yokohama",
  "Valencia-Tokyo",
  "Valencia-Osaka",
  "Valencia-Yokohama",
  "Malaga-Tokyo",
  "Malaga-Osaka",
  "Malaga-Yokohama",
  "Barcelona-New York",
  "Barcelona-Los Angeles",
  "Barcelona-Miami",
  "Valencia-New York",
  "Valencia-Los Angeles",
  "Valencia-Miami",
  "Malaga-New York",
  "Malaga-Los Angeles",
  "Malaga-Miami",
  "Buenos Aires-Tokyo",
  "Buenos Aires-Osaka",
  "Buenos Aires-Yokohama",
  "Rosario-Tokyo",
  "Rosario-Osaka",
  "Rosario-Yokohama",
  "Mar del Plata-Tokyo",
  "Mar del Plata-Osaka",
  "Mar del Plata-Yokohama",
  "Buenos Aires-New York",
  "Buenos Aires-Los Angeles",
  "Buenos Aires-Miami",
  "Rosario-New York",
  "Rosario-Los Angeles",
  "Rosario-Miami",
  "Mar del Plata-New York",
  "Mar del Plata-Los Angeles",
  "Mar del Plata-Miami",
  "Tokyo-New York",
  "Tokyo-Los Angeles",
  "Tokyo-Miami",
  "Osaka-New York",
  "Osaka-Los Angeles",
  "Osaka-Miami",
  "Yokohama-New York",
  "Yokohama-Los Angeles",
  "Yokohama-Miami",
];

const portArray = [
  "Marseille",
  "Q23482",
  "Le Havre",
  "Q42810",
  "Bordeaux",
  "Q1479",
  "Ho Chi Minh City",
  "Q1854",
  "Haiphong",
  "Q72818",
  "Da Nang",
  "Q25282",
  "Genoa",
  "Q1449",
  "Naples",
  "Q2634",
  "Venice",
  "Q641",
  "Barcelona",
  "Q1492",
  "Valencia",
  "Q8818",
  "Malaga",
  "Q8851",
  "Buenos Aires",
  "Q1486",
  "Rosario",
  "Q52535",
  "Mar del Plata",
  "Q52607",
  "Tokyo",
  "Q1490",
  "Osaka",
  "Q35765",
  "Yokohama",
  "Q38283",
  "New York",
  "Q60",
  "Los Angeles",
  "Q65",
  "Miami",
  "Q8652",
];

async function getDistance(city1: string, city2: string) {
  const options = {
    method: "GET",
    url: `https://wft-geo-db.p.rapidapi.com/v1/geo/cities/${city1}/distance`,
    params: { toCityId: city2, distanceUnit: "KM" },
    headers: {
      "X-RapidAPI-Key": "32c6f72a50msha7ea0bba90d1e74p1d8bd9jsncdd8d5d3f0bd",
      "X-RapidAPI-Host": "wft-geo-db.p.rapidapi.com",
    },
  };

  try {
    const response = await axios.request(options);
    return response.data.data;
  } catch (error) {
    // console.error(error);
  }
}

const delay = (ms: any) => new Promise((resolve) => setTimeout(resolve, ms));

const main = async () => {
  const portCode = new Map();

  for (let i = 0; i < portArray.length; i += 2) {
    const portName = portArray[i];
    const wikidataId = portArray[i + 1];
    portCode.set(portName, wikidataId);
  }

  console.log("[");
  for (let pair of portPair) {
    const [port1, port2] = pair.split("-");
    const port1Code = portCode.get(port1);
    const port2Code = portCode.get(port2);
    const distance = await getDistance(port1Code, port2Code);
    console.log(`["${pair}", "${distance}"],`);
    await delay(1000);
  }
  console.log("]");
};

main();
